name: AdminTools #old n dead project
version: Beta 1.1
main: me.mrdev.AdminTools
commands:
   vanish:
      description: A vanish command !!
   PlayerList:
      description: A gui version of List command !!
